### ISSUE TITLE
Obligatory mod not supported in newest BG version Patch #7

### ISSUE THREAD

**Issue by Skeltpr** [Ch4nKyy/BG3WASD#44]
No rush... but also like this game is unplayable without this mod. 😅  Thank you so much!

**Comment by luoxh8** [comment]
Agree, without this mod, it is very difficult to control the movement of the character in certain situations, which is very inconvenient.

**Comment by yegorski** [comment]
Really enjoyed this mod pre-patch 7. After seeing the [release notes on nexusmods](https://www.nexusmods.com/baldursgate3/mods/781) for 1.9.5 patch I gave this amazing mod another shot on my win10 PC.

But WASD mvmt isn't working on patch 7. After cleanly installing -- tried both manually and via Vortex. I even nuked game folder and AppData and reinstalled BG3 cleanly just for this to work but no avail.

I see that you fixed WASD for patch 7 a day after this issue was reported so I assume others are using it successfully. Any idea what's wrong?

**Comment by Ch4nKyy** [comment]
What's the error pattern? There is a FAQ on Nexusmods. You can also post the question on Nexusmods, then the community can help.

**Comment by yegorski** [comment]
Fixed by reinstalling via Vortex. (The issue was that the mod seemed to have but the wasd keys weren't moving the character.) All's well in the world again!

Details: I removed all mods from Vortex, updated it to latest version (1.12.6) and reinstalled Native Mod Loader and WASD. The issue also may have been due to a silent failure from a mod called "LSLib/Divine Tool" missing. Once Vortex was updated, it prompted to install it for BG3 specifically.
