### ISSUE TITLE
Button to reduce movespeed to walking

### ISSUE THREAD

**Issue by Ch4nKyy** [Ch4nKyy/BG3WASD#5]
Not high prio, but I noted the wish down :)

I think this should be possible.
Instead of mapping the keypress to FULL POWER, we somehow have to map it to a value that represents like a half-pushed stick, see SDL2 documentation.
And well, it must be toggleable.

**Comment by BlackburnUTG** [comment]
oh yeah, the walking feature is the must have for me) hope you figure it out)
on gamepad you can walk with sticks..

**Comment by Ch4nKyy** [comment]
@ersh1 
Hi,

On the linked branch I posted a proof of concept in the form of a CE table regarding the toggle between running and walking speed.
The easiest thing I came up with:
-Inject code that divides the movement input value by a certain amount (speed_divisor).
-Manipulate this divisor through an AHK script with classMemory

Until now the mod only needed to replace instructions. Do you have an example how to inject or hook code with DKUtils?

Another question is how AHK can know which address it has to manipulate.
I came up with the idea of this dummy variable called aobtarget. Basically, this dummy should reside directly in front of speed_divisor and it should have a very distinct value, so it can be found with an AOB scan easily.
Alternatively, the DLL could write the address to a file and AHK could read it.

**Comment by gottyduke** [comment]
Just my two cents on this: instead of scanning a variable, it'd be better to scan the code that accesses/writes to it, then interject the result and tamper with it from there.

**Comment by Ch4nKyy** [comment]
Hm I am not sure if I understand you right. And if you understand my intention.

My goal is to manipulate the movement input variable to enable walking slowly.
I scan for the code that writes this variable and inject code that divides it by a divisor.
This divisor is an injected variable and to the code it looks constant, because it is never written, only read.

But I want the divisor to be toggleable. E.g. 1.0 for running, 5.0 for walking.
Implementing key input is easier done in AHK than in injected code I think?
That is why I create an AHK hotkey that manipulates the divisor. But to do that, I need to know the address of the divisor inside the AHK script.

**Comment by gottyduke** [comment]
My bad, I was presuming the key input toggle is done in code. thought the problem was how to scan the variable. I would suggest doing both of them in code, since you are already implementing though dll.

**Comment by Ch4nKyy** [comment]
Do you, perchance, have existing projects that could illustrate these two techniques for me?
I mean I know what you mean, but I never implemented this stuff in this DLL injection fashion before. And I assume this has been done a thousand times.

**Comment by gottyduke** [comment]
Sure, since you are already using DKUtil, here's a basic demo:
https://gist.github.com/gottyduke/408666aeee2cc1f96767712cdbf57b8f

**Comment by gottyduke** [comment]
> Ok, so with ASM Patch I can patch assembly. I can even inject more code than there is space, because then it will automatically jump to a "trampoline", right? And the trampoline space I alloc once in the beginning.
>
Yes. But if you are committing more than there is space, you'd need to make sure it's at least 5 bytes for jumping to trampoline.
Example: you wanted to patch this:
```asm
mov rcx, rax // this is only 3 bytes
```
You'd need to include more bytes:
```asm
push rcx // previous instruction
mov rcx, rax // combined 5 bytes
// or you can pick the one after
```

> With Detour I can create a hook, but only on call/jmp instructions? And the original function will not be executed? Can I somehow take or return data? Why/when does Detour need a trampoline?
>
Detour is just a simple way of replacing a `call Game.exe+0x123456` to `call MyPlugin.dll+0x654321` style, it strips off the unused patching abilities. As you could see in the doc, the original func is returned by the call itself `write_call<5>`, and you can save that to a `std::add_pointer_t` object(or typedef but ugly) with the same function signature as the original one, to use it later, simple call it as if it were a function. `func(args...)`

> And Cave Hook can create a hook anywhere? I still have to use the base/begin address of a function, but with OffsetL I can target a specific instruction inside the function? The Prolog/Epilog patches will be applied starting from OffsetL? And then they overwrite until OffsetH. And if the patch is bigger than that, it will write to the trampoline and jump there and return after? So just like ASM Patch? 
> 
Cave hook yes does create a hook anywhere, the OffsetL could be `0` if you set the base directly to where you needed it. I just found it easier to work with pattern scanners, because pattern scanners return the base address of function, so I manually specify the offset for better readablity. Cave hook is meant to use **with** a hook function, that it will detour to, with patches prepended/appended, optionally restore the original asm bytes using the `HookFlag`.
Here's an example weeks ago I made for others, it's used for Skyrim modding (SKSE plugins) but the core is the same.
https://gist.github.com/gottyduke/f5ec8bedb263d0d1689dcdbb60f78819

> Does the hook return to OffsetH or to OffsetL?
>
Any hook **besides** Detours will return a `HookHandle` result object, you can then access the related properties of this hook operation from it, and `handle->Enable()` or `Disable()` the hook.

>  Again, can this hook take or return data? If yes, which registers will it read/write?
>
As for returning values, or to take return value, all of it would comply with [x64 Calling Convention](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170), so you can work from there.

---
Lastly, a basic example of replacing a custom float with your own version:
assume we have an instruction like this:
```asm
00007FF7539B01F1 | movups xmm6,xmmword ptr ss:[rsp+0x1A0]
``` 
And we want to replace xmm6 with our own version, through some functions.
You'd do this:
https://gist.github.com/gottyduke/8da4bff5f366349cef59720890eb3914

Hooking with memory patches is prone to error, which I believe you've already known that.
